version: "3"

services:
  api:
    container_name: api
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - docker/env/db.env
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    tty: true
    networks:
      - backend
  db:
    container_name: db
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    env_file:
      - docker/env/db.env
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    tty: true
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  postgres_data: