version: "3"

services:
  api:
    container_name: api
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    tty: true
    networks:
      - backend
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    env_file:
      - docker/env/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  postgres_data: